//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public Computer()
        {
            this.UsedOns = new HashSet<UsedOn>();
        }
    
        public int ComputerId { get; set; }
        public string Hostname { get; set; }
        public string IpAddress { get; set; }
        public string Location { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<UsedOn> UsedOns { get; set; }
    }
}
