//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public Computer()
        {
            this.UsedOns = new HashSet<UsedOn>();
        }
    
        public int ComputerId { get; set; }
        public string Hostname { get; set; }
        public string IpAddress { get; set; }
        public string Location { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<UsedOn> UsedOns { get; set; }
    }
}
