//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public License()
        {
            this.UsedOns = new HashSet<UsedOn>();
        }
    
        public int LicenseId { get; set; }
        public int SoftwareId { get; set; }
        public string Edition { get; set; }
        public string ActivationKey { get; set; }
        public Nullable<byte> VolumeLicense { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual Software Software { get; set; }
        public virtual ICollection<UsedOn> UsedOns { get; set; }
    }
}
