//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public License()
        {
            this.UsedOns = new HashSet<UsedOn>();
        }
    
        public int LicenseId { get; set; }
        public int SoftwareId { get; set; }
        public string Edition { get; set; }
        public string ActivationKey { get; set; }
        public Nullable<byte> VolumeLicense { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual Software Software { get; set; }
        public virtual ICollection<UsedOn> UsedOns { get; set; }
    }
}
