//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager.Shared
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LicenseManagerEntities : DbContext
    {
        public LicenseManagerEntities()
            : base("name=LicenseManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Computer> Computers { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<License> Licenses { get; set; }
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<Software> Softwares { get; set; }
        public DbSet<UsedOn> UsedOns { get; set; }
    }
}
