//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager.Shared
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LicenseManagerEntities : DbContext
    {
        public LicenseManagerEntities()
            : base("name=LicenseManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Computer> Computers { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<License> Licenses { get; set; }
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<Software> Softwares { get; set; }
        public DbSet<UsedOn> UsedOns { get; set; }
    }
}
