//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        public Software()
        {
            this.Licenses = new HashSet<License>();
        }
    
        public int SoftwareId { get; set; }
        public int ManufacturerId { get; set; }
        public int GenreId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual ICollection<License> Licenses { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
