//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        public Software()
        {
            this.Licenses = new HashSet<License>();
        }
    
        public int SoftwareId { get; set; }
        public int ManufacturerId { get; set; }
        public int GenreId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual ICollection<License> Licenses { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
