//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedOn
    {
        public string UsedOnId { get; set; }
        public int ComputerId { get; set; }
        public int LicenseId { get; set; }
        public System.DateTime InstallationDate { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual License License { get; set; }
    }
}
