//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManager.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedOn
    {
        public string UsedOnId { get; set; }
        public int ComputerId { get; set; }
        public int LicenseId { get; set; }
        public System.DateTime InstallationDate { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual License License { get; set; }
    }
}
